[project]
name = "whisper-numpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "einops>=0.8.2",
    "icecream>=2.2.0",
    "ipykernel>=7.2.0",
    "notebook>=7.5.6",
    "numpy>=2.4.6",
    "openai-whisper>=20250625",
    "scipy>=1.17.1",
    "torch>=2.12.0",
]
